# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 16:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=255)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
