# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 16:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metapile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
